# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew && chmod +x catbox
    - name: Download production GS
      env: # Or as an environment variable
        gs_url: ${{ secrets.GS_URL }}
      run: wget -q -O app/google-services.json $gs_url
    - name: Build with Gradle
      run: ./gradlew build assembleDebug --stacktrace
    - name: Move apk
      run: mkdir -p uploads && mv app/build/outputs/apk/debug/app-debug.apk uploads/
    - name: Send telegram Message
      env:
        bot_token: ${{ secrets.BOT_TOKEN }}
      run: curl -v --silent -F caption="$(git log --decorate=no --oneline -1)  $(./catbox file uploads/app-debug.apk)" -F chat_id="459034222" -F document=@"$PWD/uploads/app-debug.apk" https://api.telegram.org/bot$bot_token/sendDocument
    - name: Upload APK
      uses: actions/upload-artifact@v2-preview
      with:
        name: app.apk
        path: uploads/app-debug.apk